name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks! I owe you a coffee!'
        pr-message: 'Thanks! You made sure that the world is a better place.'
